[package]
name = "rapid_discovery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jwalk = "0.6.0"
polars = {version = "0.25.1", features = ["describe", "lazy"]}
crc32fast = "1.3.2"
